cache: bundler
rvm:
- 2.3.1
- 2.4.0-preview2
services:
- redis-server
before_script:
- export CODECLIMATE_REPO_TOKEN=4420fcc110f74e4f517b30001c3655f83f727db789e1798f2433c3fa7e38fc7a
script: bundle exec rspec
notifications:
  slack:
    secure: cNKoNTiCn5PoVQ/zIDEGS7muWJ4KWsCMmy8nMJVUaa1lK+IBfD2c5RuBlBERcdqbihm17j7XWa66PCQ89PKYvFKNJcUH0UmyvliY7Yu66ljYid22zb9CGXxvN2Nlosz7WGr8zUePttyBe89tx2Fnrvywfq047qE67KQtRGcRNHohyaxkc1G21bsDeDA2zzaYo1o8F3wZS0v/4COlMWjz9gCYkupjewYk0dlNSAnwQ+6sX0NYkpOrlobjP+L6au2SyLyPCfTBjmJdUS7/syt0Yg0hD0PXgCp4V2C7dIRqahpPwsw2p30/u4kwdobKC7+bzV8zoysewYgD29Up7kw0Uu/WWm3s27hK55g74nhK4PSeCuS4hnfBsxHstoKUrpoRWg6I/tG8SYCgFoHZVQePziewiKPc13vV9cgCu/mK/VtniMwknUKcKzGHN29A7z3vMWgDWmAgvipyYRbnsTOyCQLZdXOcWNclCzLwYjMe6V3gqo9ZIkvr0alWhUrBdyFKUYQINjo5ZlwjTiH11OwDUQGQ9eTuuqXZCoe5xWXdXRIFSXmdJuUz4v5fX23SfeCfLTLX+JpDVsndIlOSeEJCzhM5b1KxtHCbcnyax1mgTOKPx6ZyxnLIPiOjIdvTOlzfK2e6J403jwBq+PZyhUrISC+VLErl8NoUIT5t5uJJPeo=
env:
  global:
  - CODECLIMATE_REPO_TOKEN=4420fcc110f74e4f517b30001c3655f83f727db789e1798f2433c3fa7e38fc7a
